<?php # -*- coding: utf-8 -*-

namespace PHPSTORM_META {

	$STATIC_METHOD_TYPES = [
		new \Inpsyde\MultilingualPress\Service\Container            => [
			'' == '@',

			'multilingualpress.active_plugins' instanceof \Inpsyde\MultilingualPress\SiteDuplication\ActivePlugins,
			'multilingualpress.asset_factory' instanceof \Inpsyde\MultilingualPress\Asset\AssetFactory,
			'multilingualpress.asset_manager' instanceof \Inpsyde\MultilingualPress\Asset\AssetManager,
			'multilingualpress.attachment_copier' instanceof \Inpsyde\MultilingualPress\SiteDuplication\AttachmentCopier,
			'multilingualpress.base_path_adapter' instanceof \Inpsyde\MultilingualPress\Common\BasePathAdapter,
			'multilingualpress.content_relations' instanceof \Inpsyde\MultilingualPress\API\ContentRelations,
			'multilingualpress.content_relations_table' instanceof \Inpsyde\MultilingualPress\Database\Table,
			'multilingualpress.error_factory' instanceof \Inpsyde\MultilingualPress\Factory\ErrorFactory,
			'multilingualpress.installer' instanceof \Inpsyde\MultilingualPress\Installation\Installer,
			'multilingualpress.internal_locations' instanceof \Inpsyde\MultilingualPress\Core\InternalLocations,
			'multilingualpress.languages_table' instanceof \Inpsyde\MultilingualPress\Database\Table,
			'multilingualpress.module_manager' instanceof \Inpsyde\MultilingualPress\Module\ModuleManager,
			'multilingualpress.network_plugin_deactivator' instanceof \Inpsyde\MultilingualPress\Installation\NetworkPluginDeactivator,
			'multilingualpress.nonce_factory' instanceof \Inpsyde\MultilingualPress\Factory\FallbackNonceFactory,
			'multilingualpress.plugin_settings_page' instanceof \Inpsyde\MultilingualPress\Common\Admin\SettingsPage,
			'multilingualpress.plugin_settings_page_view' instanceof \Inpsyde\MultilingualPress\Core\Admin\PluginSettingsPage\View,
			'multilingualpress.plugin_settings_updater' instanceof \Inpsyde\MultilingualPress\Core\Admin\PluginSettingsPage\PluginSettingsUpdater,
			'multilingualpress.post_type_link_url_filter' instanceof \Inpsyde\MultilingualPress\Module\CustomPostTypeSupport\URLFilter,
			'multilingualpress.post_type_repository' instanceof \Inpsyde\MultilingualPress\Module\CustomPostTypeSupport\PostTypeRepository,
			'multilingualpress.post_type_support_settings_box' instanceof \Inpsyde\MultilingualPress\Common\Setting\SettingsBoxViewModel,
			'multilingualpress.post_type_support_settings_nonce' instanceof \Inpsyde\MultilingualPress\Common\Nonce\Nonce,
			'multilingualpress.post_type_support_settings_updater' instanceof \Inpsyde\MultilingualPress\Module\CustomPostTypeSupport\PostTypeSupportSettingsUpdater,
			'multilingualpress.properties' instanceof \Inpsyde\MultilingualPress\Common\PluginProperties,
			'multilingualpress.site_duplication_settings_view' instanceof \Inpsyde\MultilingualPress\SiteDuplication\SettingsView,
			'multilingualpress.site_duplicator' instanceof \Inpsyde\MultilingualPress\SiteDuplication\SiteDuplicator,
			'multilingualpress.site_relations' instanceof \Inpsyde\MultilingualPress\API\SiteRelations,
			'multilingualpress.site_relations_table' instanceof \Inpsyde\MultilingualPress\Database\Table,
			'multilingualpress.system_checker' instanceof \Inpsyde\MultilingualPress\Installation\SystemChecker,
			'multilingualpress.table_duplicator' instanceof \Inpsyde\MultilingualPress\Database\TableDuplicator,
			'multilingualpress.table_installer' instanceof \Inpsyde\MultilingualPress\Database\TableInstaller,
			'multilingualpress.table_list' instanceof \Inpsyde\MultilingualPress\Database\TableList,
			'multilingualpress.table_replacer' instanceof \Inpsyde\MultilingualPress\Database\TableReplacer,
			'multilingualpress.table_string_replacer' instanceof \Inpsyde\MultilingualPress\Database\TableStringReplacer,
			'multilingualpress.translation_completed_setting_nonce' instanceof \Inpsyde\MultilingualPress\Common\Nonce\Nonce,
			'multilingualpress.translation_completed_setting_updater' instanceof \Inpsyde\MultilingualPress\Widget\Dashboard\UntranslatedPosts\TranslationCompletedSettingUpdater,
			'multilingualpress.translation_completed_setting_view' instanceof \Inpsyde\MultilingualPress\Widget\Dashboard\UntranslatedPosts\TranslationCompletedSettingView,
			'multilingualpress.trasher' instanceof \Inpsyde\MultilingualPress\Module\Trasher\Trasher,
			'multilingualpress.trasher_setting_nonce' instanceof \Inpsyde\MultilingualPress\Common\Nonce\Nonce,
			'multilingualpress.trasher_setting_repository' instanceof \Inpsyde\MultilingualPress\Module\Trasher\TrasherSettingRepository,
			'multilingualpress.trasher_setting_updater' instanceof \Inpsyde\MultilingualPress\Module\Trasher\TrasherSettingUpdater,
			'multilingualpress.trasher_setting_view' instanceof \Inpsyde\MultilingualPress\Module\Trasher\TrasherSettingView,
			'multilingualpress.type_factory' instanceof \Inpsyde\MultilingualPress\Factory\TypeFactory,
			'multilingualpress.untranslated_posts_dashboard_widget' instanceof \Inpsyde\MultilingualPress\Widget\Dashboard\DashboardWidget,
			'multilingualpress.untranslated_posts_dashboard_widget_view' instanceof \Inpsyde\MultilingualPress\Widget\Dashboard\View,
			'multilingualpress.untranslated_posts_repository' instanceof \Inpsyde\MultilingualPress\Widget\Dashboard\UntranslatedPosts\PostRepository,
			'multilingualpress.update_plugin_settings_nonce' instanceof \Inpsyde\MultilingualPress\Common\Nonce\Nonce,
			'multilingualpress.updater' instanceof \Inpsyde\MultilingualPress\Installation\Updater,
			'multilingualpress.user_admin_language_locale_filter' instanceof \Inpsyde\MultilingualPress\Module\UserAdminLanguage\LocaleFilter,
			'multilingualpress.user_admin_language_repository' instanceof \Inpsyde\MultilingualPress\Module\UserAdminLanguage\LanguageRepository,
		],
		\Inpsyde\MultilingualPress\MultilingualPress::resolve( '' ) => [
			'' == '@',

			'multilingualpress.asset_factory' instanceof \Inpsyde\MultilingualPress\Asset\AssetFactory,
			'multilingualpress.asset_manager' instanceof \Inpsyde\MultilingualPress\Asset\AssetManager,
			'multilingualpress.content_relations' instanceof \Inpsyde\MultilingualPress\API\ContentRelations,
			'multilingualpress.content_relations_table' instanceof \Inpsyde\MultilingualPress\Database\Table,
			'multilingualpress.error_factory' instanceof \Inpsyde\MultilingualPress\Factory\ErrorFactory,
			'multilingualpress.languages_table' instanceof \Inpsyde\MultilingualPress\Database\Table,
			'multilingualpress.network_plugin_deactivator' instanceof \Inpsyde\MultilingualPress\Installation\NetworkPluginDeactivator,
			'multilingualpress.nonce_factory' instanceof \Inpsyde\MultilingualPress\Factory\FallbackNonceFactory,
			'multilingualpress.properties' instanceof \Inpsyde\MultilingualPress\Common\PluginProperties,
			'multilingualpress.site_relations' instanceof \Inpsyde\MultilingualPress\API\SiteRelations,
			'multilingualpress.site_relations_table' instanceof \Inpsyde\MultilingualPress\Database\Table,
			'multilingualpress.table_duplicator' instanceof \Inpsyde\MultilingualPress\Database\TableDuplicator,
			'multilingualpress.table_installer' instanceof \Inpsyde\MultilingualPress\Database\TableInstaller,
			'multilingualpress.table_list' instanceof \Inpsyde\MultilingualPress\Database\TableList,
			'multilingualpress.table_replacer' instanceof \Inpsyde\MultilingualPress\Database\TableReplacer,
			'multilingualpress.table_string_replacer' instanceof \Inpsyde\MultilingualPress\Database\TableStringReplacer,
			'multilingualpress.type_factory' instanceof \Inpsyde\MultilingualPress\Factory\TypeFactory,
		],
	];
}
