<?php # -*- coding: utf-8 -*-

declare( strict_types=1 );

namespace Inpsyde\MultilingualPress\Database\Table;

use Inpsyde\MultilingualPress\Database\Table;

/**
 * Languages table.
 *
 * @package Inpsyde\MultilingualPress\Database\Table
 * @since   3.0.0
 */
final class LanguagesTable implements Table {

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_CUSTOM_NAME = 'custom_name';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_ENGLISH_NAME = 'english_name';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_HTTP_CODE = 'http_code';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_ID = 'ID';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_ISO_639_1_CODE = 'iso_639_1';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_ISO_639_2_CODE = 'iso_639_2';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_LOCALE = 'locale';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_NATIVE_NAME = 'native_name';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_PRIORITY = 'priority';

	/**
	 * Column name.
	 *
	 * @since 3.0.0
	 *
	 * @var string
	 */
	const COLUMN_RTL = 'is_rtl';

	/**
	 * @var string
	 */
	private $prefix;

	/**
	 * Constructor. Set up the properties.
	 *
	 * @since 3.0.0
	 *
	 * @param string $prefix Optional Table name prefix. Defaults to empty string.
	 */
	public function __construct( string $prefix = '' ) {

		$this->prefix = (string) $prefix;
	}

	/**
	 * Returns an array with all columns that do not have any default content.
	 *
	 * @since 3.0.0
	 *
	 * @return string[] All columns that do not have any default content.
	 */
	public function columns_without_default_content(): array {

		return [
			self::COLUMN_CUSTOM_NAME,
			self::COLUMN_ID,
		];
	}

	/**
	 * Returns the SQL string for the default content.
	 *
	 * @since 3.0.0
	 *
	 * @return string The SQL string for the default content.
	 */
	public function default_content_sql(): string {

		$rows = [
			'aa'    => [
				self::COLUMN_ENGLISH_NAME   => 'Afar',
				self::COLUMN_NATIVE_NAME    => 'Afaraf',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'aa',
				self::COLUMN_ISO_639_2_CODE => 'aar',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'aa',
				self::COLUMN_PRIORITY       => 1,
			],
			'ae'    => [
				self::COLUMN_ENGLISH_NAME   => 'Avestan',
				self::COLUMN_NATIVE_NAME    => 'avesta',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ae',
				self::COLUMN_ISO_639_2_CODE => 'ave',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ae',
				self::COLUMN_PRIORITY       => 1,
			],
			'af'    => [
				self::COLUMN_ENGLISH_NAME   => 'Afrikaans',
				self::COLUMN_NATIVE_NAME    => 'Afrikaans',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'af',
				self::COLUMN_ISO_639_2_CODE => 'afr',
				self::COLUMN_LOCALE         => 'af',
				self::COLUMN_HTTP_CODE      => 'af-ZA',
				self::COLUMN_PRIORITY       => 1,
			],
			'ak'    => [
				self::COLUMN_ENGLISH_NAME   => 'Akan',
				self::COLUMN_NATIVE_NAME    => 'Akan',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ak',
				self::COLUMN_ISO_639_2_CODE => 'aka',
				self::COLUMN_LOCALE         => 'ak',
				self::COLUMN_HTTP_CODE      => 'ak',
				self::COLUMN_PRIORITY       => 1,
			],
			'am'    => [
				self::COLUMN_ENGLISH_NAME   => 'Amharic',
				self::COLUMN_NATIVE_NAME    => 'አማርኛ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'am',
				self::COLUMN_ISO_639_2_CODE => 'amh',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'am',
				self::COLUMN_PRIORITY       => 1,
			],
			'an'    => [
				self::COLUMN_ENGLISH_NAME   => 'Aragonese',
				self::COLUMN_NATIVE_NAME    => 'Aragonés',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'an',
				self::COLUMN_ISO_639_2_CODE => 'arg',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'an',
				self::COLUMN_PRIORITY       => 1,
			],
			'ar'    => [
				self::COLUMN_ENGLISH_NAME   => 'Arabic',
				self::COLUMN_NATIVE_NAME    => 'العربية',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'ar',
				self::COLUMN_ISO_639_2_CODE => 'ara',
				self::COLUMN_LOCALE         => 'ar',
				self::COLUMN_HTTP_CODE      => 'ar-AR',
				self::COLUMN_PRIORITY       => 1,
			],
			'as'    => [
				self::COLUMN_ENGLISH_NAME   => 'Assamese',
				self::COLUMN_NATIVE_NAME    => 'অসমীয়া',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'as',
				self::COLUMN_ISO_639_2_CODE => 'asm',
				self::COLUMN_LOCALE         => 'as',
				self::COLUMN_HTTP_CODE      => 'asm',
				self::COLUMN_PRIORITY       => 1,
			],
			'ast'   => [
				self::COLUMN_ENGLISH_NAME   => 'Asturian',
				self::COLUMN_NATIVE_NAME    => 'Asturianu',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => 'ast',
				self::COLUMN_LOCALE         => 'ast',
				self::COLUMN_HTTP_CODE      => 'ast',
				self::COLUMN_PRIORITY       => 1,
			],
			'av'    => [
				self::COLUMN_ENGLISH_NAME   => 'Avaric',
				self::COLUMN_NATIVE_NAME    => 'авар мацӀ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'av',
				self::COLUMN_ISO_639_2_CODE => 'ava',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'av',
				self::COLUMN_PRIORITY       => 1,
			],
			'ay'    => [
				self::COLUMN_ENGLISH_NAME   => 'Aymara',
				self::COLUMN_NATIVE_NAME    => 'aymar aru',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ay',
				self::COLUMN_ISO_639_2_CODE => 'aym',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ay',
				self::COLUMN_PRIORITY       => 1,
			],
			'az'    => [
				self::COLUMN_ENGLISH_NAME   => 'Azerbaijani',
				self::COLUMN_NATIVE_NAME    => 'Azərbaycan dili',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'az',
				self::COLUMN_ISO_639_2_CODE => 'aze',
				self::COLUMN_LOCALE         => 'az',
				self::COLUMN_HTTP_CODE      => 'az-AZ',
				self::COLUMN_PRIORITY       => 1,
			],
			'azb'   => [
				self::COLUMN_ENGLISH_NAME   => 'South Azerbaijani',
				self::COLUMN_NATIVE_NAME    => 'گؤنئی آذربایجان',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'az',
				self::COLUMN_ISO_639_2_CODE => 'aze',
				self::COLUMN_LOCALE         => 'azb',
				self::COLUMN_HTTP_CODE      => 'az',
				self::COLUMN_PRIORITY       => 1,
			],
			'az-tr' => [
				self::COLUMN_ENGLISH_NAME   => 'Azerbaijani (Turkey)',
				self::COLUMN_NATIVE_NAME    => 'Azərbaycan Türkcəsi',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'az',
				self::COLUMN_ISO_639_2_CODE => 'aze',
				self::COLUMN_LOCALE         => 'az_TR',
				self::COLUMN_HTTP_CODE      => 'az-TR',
				self::COLUMN_PRIORITY       => 1,
			],
			'ba'    => [
				self::COLUMN_ENGLISH_NAME   => 'Bashkir',
				self::COLUMN_NATIVE_NAME    => 'башҡорт теле',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ba',
				self::COLUMN_ISO_639_2_CODE => 'bak',
				self::COLUMN_LOCALE         => 'ba',
				self::COLUMN_HTTP_CODE      => 'ba',
				self::COLUMN_PRIORITY       => 1,
			],
			'bal'   => [
				self::COLUMN_ENGLISH_NAME   => 'Catalan (Balear)',
				self::COLUMN_NATIVE_NAME    => 'Català (Balear)',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ca',
				self::COLUMN_ISO_639_2_CODE => 'cat',
				self::COLUMN_LOCALE         => 'bal',
				self::COLUMN_HTTP_CODE      => 'ca',
				self::COLUMN_PRIORITY       => 1,
			],
			'bel'   => [
				self::COLUMN_ENGLISH_NAME   => 'Belarusian',
				self::COLUMN_NATIVE_NAME    => 'Беларуская мова',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'be',
				self::COLUMN_ISO_639_2_CODE => 'bel',
				self::COLUMN_LOCALE         => 'bel',
				self::COLUMN_HTTP_CODE      => 'be-BY',
				self::COLUMN_PRIORITY       => 1,
			],
			'bg'    => [
				self::COLUMN_ENGLISH_NAME   => 'Bulgarian',
				self::COLUMN_NATIVE_NAME    => 'Български',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'bg',
				self::COLUMN_ISO_639_2_CODE => 'bul',
				self::COLUMN_LOCALE         => 'bg_BG',
				self::COLUMN_HTTP_CODE      => 'bg-BG',
				self::COLUMN_PRIORITY       => 1,
			],
			'bh'    => [
				self::COLUMN_ENGLISH_NAME   => 'Bihari',
				self::COLUMN_NATIVE_NAME    => 'भोजपुरी',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'bh',
				self::COLUMN_ISO_639_2_CODE => 'bih',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'bh',
				self::COLUMN_PRIORITY       => 1,
			],
			'bi'    => [
				self::COLUMN_ENGLISH_NAME   => 'Bislama',
				self::COLUMN_NATIVE_NAME    => 'Bislama',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'bi',
				self::COLUMN_ISO_639_2_CODE => 'bis',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'bi',
				self::COLUMN_PRIORITY       => 1,
			],
			'bm'    => [
				self::COLUMN_ENGLISH_NAME   => 'Bambara',
				self::COLUMN_NATIVE_NAME    => 'Bamanankan',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'bm',
				self::COLUMN_ISO_639_2_CODE => 'bam',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'bm',
				self::COLUMN_PRIORITY       => 1,
			],
			'bn'    => [
				self::COLUMN_ENGLISH_NAME   => 'Bengali',
				self::COLUMN_NATIVE_NAME    => 'বাংলা',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'bn',
				self::COLUMN_ISO_639_2_CODE => 'ben',
				self::COLUMN_LOCALE         => 'bn_BD',
				self::COLUMN_HTTP_CODE      => 'bn-BD',
				self::COLUMN_PRIORITY       => 1,
			],
			'bo'    => [
				self::COLUMN_ENGLISH_NAME   => 'Tibetan',
				self::COLUMN_NATIVE_NAME    => 'བོད་སྐད',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'bo',
				self::COLUMN_ISO_639_2_CODE => 'bod',
				self::COLUMN_LOCALE         => 'bo',
				self::COLUMN_HTTP_CODE      => 'bo',
				self::COLUMN_PRIORITY       => 1,
			],
			'br'    => [
				self::COLUMN_ENGLISH_NAME   => 'Breton',
				self::COLUMN_NATIVE_NAME    => 'brezhoneg',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'br',
				self::COLUMN_ISO_639_2_CODE => 'bre',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'br',
				self::COLUMN_PRIORITY       => 1,
			],
			'bs'    => [
				self::COLUMN_ENGLISH_NAME   => 'Bosnian',
				self::COLUMN_NATIVE_NAME    => 'Bosanski',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'bs',
				self::COLUMN_ISO_639_2_CODE => 'bos',
				self::COLUMN_LOCALE         => 'bs_BA',
				self::COLUMN_HTTP_CODE      => 'bs-BA',
				self::COLUMN_PRIORITY       => 1,
			],
			'ca'    => [
				self::COLUMN_ENGLISH_NAME   => 'Catalan',
				self::COLUMN_NATIVE_NAME    => 'Català',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ca',
				self::COLUMN_ISO_639_2_CODE => 'cat',
				self::COLUMN_LOCALE         => 'ca',
				self::COLUMN_HTTP_CODE      => 'ca-ES',
				self::COLUMN_PRIORITY       => 1,
			],
			'ce'    => [
				self::COLUMN_ENGLISH_NAME   => 'Chechen',
				self::COLUMN_NATIVE_NAME    => 'Нохчийн мотт',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ce',
				self::COLUMN_ISO_639_2_CODE => 'che',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ce',
				self::COLUMN_PRIORITY       => 1,
			],
			'ch'    => [
				self::COLUMN_ENGLISH_NAME   => 'Chamorro',
				self::COLUMN_NATIVE_NAME    => 'Chamoru',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ch',
				self::COLUMN_ISO_639_2_CODE => 'cha',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ch',
				self::COLUMN_PRIORITY       => 1,
			],
			'ckb'   => [
				self::COLUMN_ENGLISH_NAME   => 'Kurdish (Sorani)',
				self::COLUMN_NATIVE_NAME    => 'كوردی‎',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ku',
				self::COLUMN_ISO_639_2_CODE => 'kur',
				self::COLUMN_LOCALE         => 'ckb',
				self::COLUMN_HTTP_CODE      => 'ku',
				self::COLUMN_PRIORITY       => 1,
			],
			'co'    => [
				self::COLUMN_ENGLISH_NAME   => 'Corsican',
				self::COLUMN_NATIVE_NAME    => 'corsu',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'co',
				self::COLUMN_ISO_639_2_CODE => 'cos',
				self::COLUMN_LOCALE         => 'co',
				self::COLUMN_HTTP_CODE      => 'co',
				self::COLUMN_PRIORITY       => 1,
			],
			'cr'    => [
				self::COLUMN_ENGLISH_NAME   => 'Cree',
				self::COLUMN_NATIVE_NAME    => 'ᓀᐦᐃᔭᐍᐏᐣ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'cr',
				self::COLUMN_ISO_639_2_CODE => 'cre',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'cr',
				self::COLUMN_PRIORITY       => 1,
			],
			'cs'    => [
				self::COLUMN_ENGLISH_NAME   => 'Czech',
				self::COLUMN_NATIVE_NAME    => 'čeština‎',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'cs',
				self::COLUMN_ISO_639_2_CODE => 'cze',
				self::COLUMN_LOCALE         => 'cs_CZ',
				self::COLUMN_HTTP_CODE      => 'cs-CZ',
				self::COLUMN_PRIORITY       => 1,
			],
			'csb'   => [
				self::COLUMN_ENGLISH_NAME   => 'Kashubian',
				self::COLUMN_NATIVE_NAME    => 'Kaszëbsczi',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => 'csb',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'csb',
				self::COLUMN_PRIORITY       => 1,
			],
			'cu'    => [
				self::COLUMN_ENGLISH_NAME   => 'Church Slavic',
				self::COLUMN_NATIVE_NAME    => 'ѩзыкъ словѣньскъ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'cu',
				self::COLUMN_ISO_639_2_CODE => 'chu',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'cu',
				self::COLUMN_PRIORITY       => 1,
			],
			'cv'    => [
				self::COLUMN_ENGLISH_NAME   => 'Chuvash',
				self::COLUMN_NATIVE_NAME    => 'чӑваш чӗлхи',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'cv',
				self::COLUMN_ISO_639_2_CODE => 'chv',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'cv',
				self::COLUMN_PRIORITY       => 1,
			],
			'cy'    => [
				self::COLUMN_ENGLISH_NAME   => 'Welsh',
				self::COLUMN_NATIVE_NAME    => 'Cymraeg',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'cy',
				self::COLUMN_ISO_639_2_CODE => 'cym',
				self::COLUMN_LOCALE         => 'cy',
				self::COLUMN_HTTP_CODE      => 'cy-GB',
				self::COLUMN_PRIORITY       => 1,
			],
			'da'    => [
				self::COLUMN_ENGLISH_NAME   => 'Danish',
				self::COLUMN_NATIVE_NAME    => 'Dansk',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'da',
				self::COLUMN_ISO_639_2_CODE => 'dan',
				self::COLUMN_LOCALE         => 'da_DK',
				self::COLUMN_HTTP_CODE      => 'da-DK',
				self::COLUMN_PRIORITY       => 1,
			],
			'de'    => [
				self::COLUMN_ENGLISH_NAME   => 'German',
				self::COLUMN_NATIVE_NAME    => 'Deutsch',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'de',
				self::COLUMN_ISO_639_2_CODE => 'deu',
				self::COLUMN_LOCALE         => 'de_DE',
				self::COLUMN_HTTP_CODE      => 'de-DE',
				self::COLUMN_PRIORITY       => 1,
			],
			'dv'    => [
				self::COLUMN_ENGLISH_NAME   => 'Divehi',
				self::COLUMN_NATIVE_NAME    => 'ދިވެހި',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'dv',
				self::COLUMN_ISO_639_2_CODE => 'div',
				self::COLUMN_LOCALE         => 'dv',
				self::COLUMN_HTTP_CODE      => 'dv',
				self::COLUMN_PRIORITY       => 1,
			],
			'dz'    => [
				self::COLUMN_ENGLISH_NAME   => 'Dzongkha',
				self::COLUMN_NATIVE_NAME    => 'རྫོང་ཁ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'dz',
				self::COLUMN_ISO_639_2_CODE => 'dzo',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'dz',
				self::COLUMN_PRIORITY       => 1,
			],
			'ee'    => [
				self::COLUMN_ENGLISH_NAME   => 'Ewe',
				self::COLUMN_NATIVE_NAME    => 'Eʋegbe',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ee',
				self::COLUMN_ISO_639_2_CODE => 'ewe',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ee',
				self::COLUMN_PRIORITY       => 1,
			],
			'el-po' => [
				self::COLUMN_ENGLISH_NAME   => 'Greek (Polytonic)',
				self::COLUMN_NATIVE_NAME    => 'Greek (Polytonic)',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => 'grc',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'grc',
				self::COLUMN_PRIORITY       => 1,
			],
			'el'    => [
				self::COLUMN_ENGLISH_NAME   => 'Greek',
				self::COLUMN_NATIVE_NAME    => 'Ελληνικά',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'el',
				self::COLUMN_ISO_639_2_CODE => 'ell',
				self::COLUMN_LOCALE         => 'el',
				self::COLUMN_HTTP_CODE      => 'el-GR',
				self::COLUMN_PRIORITY       => 1,
			],
			'en'    => [
				self::COLUMN_ENGLISH_NAME   => 'English',
				self::COLUMN_NATIVE_NAME    => 'English',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'en',
				self::COLUMN_ISO_639_2_CODE => 'eng',
				self::COLUMN_LOCALE         => 'en_US',
				self::COLUMN_HTTP_CODE      => 'en-US',
				self::COLUMN_PRIORITY       => 1,
			],
			'en-au' => [
				self::COLUMN_ENGLISH_NAME   => 'English (Australia)',
				self::COLUMN_NATIVE_NAME    => 'English (Australia)',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'en',
				self::COLUMN_ISO_639_2_CODE => 'eng',
				self::COLUMN_LOCALE         => 'en_AU',
				self::COLUMN_HTTP_CODE      => 'en-AU',
				self::COLUMN_PRIORITY       => 1,
			],
			'en-ca' => [
				self::COLUMN_ENGLISH_NAME   => 'English (Canada)',
				self::COLUMN_NATIVE_NAME    => 'English (Canada)',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'en',
				self::COLUMN_ISO_639_2_CODE => 'eng',
				self::COLUMN_LOCALE         => 'en_CA',
				self::COLUMN_HTTP_CODE      => 'en-CA',
				self::COLUMN_PRIORITY       => 1,
			],
			'en-gb' => [
				self::COLUMN_ENGLISH_NAME   => 'English (UK)',
				self::COLUMN_NATIVE_NAME    => 'English (UK)',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'en',
				self::COLUMN_ISO_639_2_CODE => 'eng',
				self::COLUMN_LOCALE         => 'en_GB',
				self::COLUMN_HTTP_CODE      => 'en-GB',
				self::COLUMN_PRIORITY       => 1,
			],
			'en-nz' => [
				self::COLUMN_ENGLISH_NAME   => 'English (New Zealand)',
				self::COLUMN_NATIVE_NAME    => 'English (New Zealand)',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'en',
				self::COLUMN_ISO_639_2_CODE => 'eng',
				self::COLUMN_LOCALE         => 'en_NZ',
				self::COLUMN_HTTP_CODE      => 'en-NZ',
				self::COLUMN_PRIORITY       => 1,
			],
			'eo'    => [
				self::COLUMN_ENGLISH_NAME   => 'Esperanto',
				self::COLUMN_NATIVE_NAME    => 'Esperanto',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'eo',
				self::COLUMN_ISO_639_2_CODE => 'epo',
				self::COLUMN_LOCALE         => 'eo',
				self::COLUMN_HTTP_CODE      => 'eo-EO',
				self::COLUMN_PRIORITY       => 1,
			],
			'es-cl' => [
				self::COLUMN_ENGLISH_NAME   => 'Spanish (Chile)',
				self::COLUMN_NATIVE_NAME    => 'Español de Chile',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'es',
				self::COLUMN_ISO_639_2_CODE => 'spa',
				self::COLUMN_LOCALE         => 'es_CL',
				self::COLUMN_HTTP_CODE      => 'es-CL',
				self::COLUMN_PRIORITY       => 1,
			],
			'es-mx' => [
				self::COLUMN_ENGLISH_NAME   => 'Spanish (Mexico)',
				self::COLUMN_NATIVE_NAME    => 'Español de México',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'es',
				self::COLUMN_ISO_639_2_CODE => 'spa',
				self::COLUMN_LOCALE         => 'es_MX',
				self::COLUMN_HTTP_CODE      => 'es-MX',
				self::COLUMN_PRIORITY       => 1,
			],
			'es-pe' => [
				self::COLUMN_ENGLISH_NAME   => 'Spanish (Peru)',
				self::COLUMN_NATIVE_NAME    => 'Español de Perú',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'es',
				self::COLUMN_ISO_639_2_CODE => 'spa',
				self::COLUMN_LOCALE         => 'es_PE',
				self::COLUMN_HTTP_CODE      => 'es-PE',
				self::COLUMN_PRIORITY       => 1,
			],
			'es-pr' => [
				self::COLUMN_ENGLISH_NAME   => 'Spanish (Puerto Rico)',
				self::COLUMN_NATIVE_NAME    => 'Español de Puerto Rico',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'es',
				self::COLUMN_ISO_639_2_CODE => 'spa',
				self::COLUMN_LOCALE         => 'es_PR',
				self::COLUMN_HTTP_CODE      => 'es-PR',
				self::COLUMN_PRIORITY       => 1,
			],
			'es-ve' => [
				self::COLUMN_ENGLISH_NAME   => 'Spanish (Venezuela)',
				self::COLUMN_NATIVE_NAME    => 'Español de Venezuela',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'es',
				self::COLUMN_ISO_639_2_CODE => 'spa',
				self::COLUMN_LOCALE         => 'es_VE',
				self::COLUMN_HTTP_CODE      => 'es-VE',
				self::COLUMN_PRIORITY       => 1,
			],
			'es-co' => [
				self::COLUMN_ENGLISH_NAME   => 'Spanish (Colombia)',
				self::COLUMN_NATIVE_NAME    => 'Español de Colombia',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'es',
				self::COLUMN_ISO_639_2_CODE => 'spa',
				self::COLUMN_LOCALE         => 'es_CO',
				self::COLUMN_HTTP_CODE      => 'es-CO',
				self::COLUMN_PRIORITY       => 1,
			],
			'es'    => [
				self::COLUMN_ENGLISH_NAME   => 'Spanish (Spain)',
				self::COLUMN_NATIVE_NAME    => 'Español',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'es',
				self::COLUMN_ISO_639_2_CODE => 'spa',
				self::COLUMN_LOCALE         => 'es_ES',
				self::COLUMN_HTTP_CODE      => 'es-ES',
				self::COLUMN_PRIORITY       => 1,
			],
			'et'    => [
				self::COLUMN_ENGLISH_NAME   => 'Estonian',
				self::COLUMN_NATIVE_NAME    => 'Eesti',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'et',
				self::COLUMN_ISO_639_2_CODE => 'est',
				self::COLUMN_LOCALE         => 'et',
				self::COLUMN_HTTP_CODE      => 'et-EE',
				self::COLUMN_PRIORITY       => 1,
			],
			'eu'    => [
				self::COLUMN_ENGLISH_NAME   => 'Basque',
				self::COLUMN_NATIVE_NAME    => 'Euskara',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'eu',
				self::COLUMN_ISO_639_2_CODE => 'eus',
				self::COLUMN_LOCALE         => 'eu',
				self::COLUMN_HTTP_CODE      => 'eu-ES',
				self::COLUMN_PRIORITY       => 1,
			],
			'fa'    => [
				self::COLUMN_ENGLISH_NAME   => 'Persian',
				self::COLUMN_NATIVE_NAME    => 'فارسی',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'fa',
				self::COLUMN_ISO_639_2_CODE => 'fas',
				self::COLUMN_LOCALE         => 'fa_IR',
				self::COLUMN_HTTP_CODE      => 'fa-IR',
				self::COLUMN_PRIORITY       => 1,
			],
			'fa-af' => [
				self::COLUMN_ENGLISH_NAME   => 'Persian (Afghanistan)',
				self::COLUMN_NATIVE_NAME    => '(فارسی (افغانستان',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'fa',
				self::COLUMN_ISO_639_2_CODE => 'eus',
				self::COLUMN_LOCALE         => 'fa_AF',
				self::COLUMN_HTTP_CODE      => 'fa-AF',
				self::COLUMN_PRIORITY       => 1,
			],
			'fi'    => [
				self::COLUMN_ENGLISH_NAME   => 'Finnish',
				self::COLUMN_NATIVE_NAME    => 'Suomi',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'fi',
				self::COLUMN_ISO_639_2_CODE => 'fin',
				self::COLUMN_LOCALE         => 'fi',
				self::COLUMN_HTTP_CODE      => 'fi-FI',
				self::COLUMN_PRIORITY       => 1,
			],
			'fj'    => [
				self::COLUMN_ENGLISH_NAME   => 'Fijian',
				self::COLUMN_NATIVE_NAME    => 'vosa Vakaviti',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'fj',
				self::COLUMN_ISO_639_2_CODE => 'fij',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'fj',
				self::COLUMN_PRIORITY       => 1,
			],
			'fo'    => [
				self::COLUMN_ENGLISH_NAME   => 'Faroese',
				self::COLUMN_NATIVE_NAME    => 'føroyskt',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'fo',
				self::COLUMN_ISO_639_2_CODE => 'fao',
				self::COLUMN_LOCALE         => 'fo',
				self::COLUMN_HTTP_CODE      => 'fo-FO',
				self::COLUMN_PRIORITY       => 1,
			],
			'fr'    => [
				self::COLUMN_ENGLISH_NAME   => 'French (France)',
				self::COLUMN_NATIVE_NAME    => 'Français',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'fr',
				self::COLUMN_ISO_639_2_CODE => 'fra',
				self::COLUMN_LOCALE         => 'fr_FR',
				self::COLUMN_HTTP_CODE      => 'fr-FR',
				self::COLUMN_PRIORITY       => 1,
			],
			'fr-be' => [
				self::COLUMN_ENGLISH_NAME   => 'French (Belgium)',
				self::COLUMN_NATIVE_NAME    => 'Français de Belgique',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'fr',
				self::COLUMN_ISO_639_2_CODE => 'fra',
				self::COLUMN_LOCALE         => 'fr_BE',
				self::COLUMN_HTTP_CODE      => 'fr-BE',
				self::COLUMN_PRIORITY       => 1,
			],
			'fr-ca' => [
				self::COLUMN_ENGLISH_NAME   => 'French (Canada)',
				self::COLUMN_NATIVE_NAME    => 'Français du Canada',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'fr',
				self::COLUMN_ISO_639_2_CODE => 'fra',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'fr-CA',
				self::COLUMN_PRIORITY       => 1,
			],
			'fr-ch' => [
				self::COLUMN_ENGLISH_NAME   => 'French (Switzerland)',
				self::COLUMN_NATIVE_NAME    => 'Français de Suisse',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'fr',
				self::COLUMN_ISO_639_2_CODE => 'fra',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'fr-CH',
				self::COLUMN_PRIORITY       => 1,
			],
			'fy'    => [
				self::COLUMN_ENGLISH_NAME   => 'Frisian',
				self::COLUMN_NATIVE_NAME    => 'Frysk',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'fy',
				self::COLUMN_ISO_639_2_CODE => 'fry',
				self::COLUMN_LOCALE         => 'fy',
				self::COLUMN_HTTP_CODE      => 'fy-NL',
				self::COLUMN_PRIORITY       => 1,
			],
			'ga'    => [
				self::COLUMN_ENGLISH_NAME   => 'Irish',
				self::COLUMN_NATIVE_NAME    => 'Gaelige',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ga',
				self::COLUMN_ISO_639_2_CODE => 'gle',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ga-IE',
				self::COLUMN_PRIORITY       => 1,
			],
			'gd'    => [
				self::COLUMN_ENGLISH_NAME   => 'Scottish Gaelic',
				self::COLUMN_NATIVE_NAME    => 'Gàidhlig',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'gd',
				self::COLUMN_ISO_639_2_CODE => 'gla',
				self::COLUMN_LOCALE         => 'gd',
				self::COLUMN_HTTP_CODE      => 'gd',
				self::COLUMN_PRIORITY       => 1,
			],
			'gl'    => [
				self::COLUMN_ENGLISH_NAME   => 'Galician',
				self::COLUMN_NATIVE_NAME    => 'Galego',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'gl',
				self::COLUMN_ISO_639_2_CODE => 'glg',
				self::COLUMN_LOCALE         => 'gl_ES',
				self::COLUMN_HTTP_CODE      => 'gl-ES',
				self::COLUMN_PRIORITY       => 1,
			],
			'gn'    => [
				self::COLUMN_ENGLISH_NAME   => 'Guaraní',
				self::COLUMN_NATIVE_NAME    => 'Avañe’ẽ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'gn',
				self::COLUMN_ISO_639_2_CODE => 'grn',
				self::COLUMN_LOCALE         => 'gn',
				self::COLUMN_HTTP_CODE      => 'gn',
				self::COLUMN_PRIORITY       => 1,
			],
			'gsw'   => [
				self::COLUMN_ENGLISH_NAME   => 'Swiss German',
				self::COLUMN_NATIVE_NAME    => 'Schwyzerdütsch',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => 'gsw',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'gu'    => [
				self::COLUMN_ENGLISH_NAME   => 'Gujarati',
				self::COLUMN_NATIVE_NAME    => 'ગુજરાતી',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'gu',
				self::COLUMN_ISO_639_2_CODE => 'guj',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'gu',
				self::COLUMN_PRIORITY       => 1,
			],
			'ha'    => [
				self::COLUMN_ENGLISH_NAME   => 'Hausa',
				self::COLUMN_NATIVE_NAME    => 'هَوُسَ',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'ha',
				self::COLUMN_ISO_639_2_CODE => 'hau',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ha',
				self::COLUMN_PRIORITY       => 1,
			],
			'haw'   => [
				self::COLUMN_ENGLISH_NAME   => 'Hawaiian',
				self::COLUMN_NATIVE_NAME    => 'Ōlelo Hawaiʻi',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => 'haw_US',
				self::COLUMN_HTTP_CODE      => 'haw-US',
				self::COLUMN_PRIORITY       => 1,
			],
			'haz'   => [
				self::COLUMN_ENGLISH_NAME   => 'Hazaragi',
				self::COLUMN_NATIVE_NAME    => 'هزاره گی',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => 'haz',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'he'    => [
				self::COLUMN_ENGLISH_NAME   => 'Hebrew',
				self::COLUMN_NATIVE_NAME    => 'עִבְרִית',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'he',
				self::COLUMN_ISO_639_2_CODE => 'heb',
				self::COLUMN_LOCALE         => 'he_IL',
				self::COLUMN_HTTP_CODE      => 'he-IL',
				self::COLUMN_PRIORITY       => 1,
			],
			'hi'    => [
				self::COLUMN_ENGLISH_NAME   => 'Hindi',
				self::COLUMN_NATIVE_NAME    => 'हिन्दी',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'hi',
				self::COLUMN_ISO_639_2_CODE => 'hin',
				self::COLUMN_LOCALE         => 'hi_IN',
				self::COLUMN_HTTP_CODE      => 'hi-IN',
				self::COLUMN_PRIORITY       => 1,
			],
			'hr'    => [
				self::COLUMN_ENGLISH_NAME   => 'Croatian',
				self::COLUMN_NATIVE_NAME    => 'Hrvatski',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'hr',
				self::COLUMN_ISO_639_2_CODE => 'hrv',
				self::COLUMN_LOCALE         => 'hr',
				self::COLUMN_HTTP_CODE      => 'hr-HR',
				self::COLUMN_PRIORITY       => 1,
			],
			'hu'    => [
				self::COLUMN_ENGLISH_NAME   => 'Hungarian',
				self::COLUMN_NATIVE_NAME    => 'Magyar',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'hu',
				self::COLUMN_ISO_639_2_CODE => 'hun',
				self::COLUMN_LOCALE         => 'hu_HU',
				self::COLUMN_HTTP_CODE      => 'hu-HU',
				self::COLUMN_PRIORITY       => 1,
			],
			'hy'    => [
				self::COLUMN_ENGLISH_NAME   => 'Armenian',
				self::COLUMN_NATIVE_NAME    => 'Հայերեն',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'hy',
				self::COLUMN_ISO_639_2_CODE => 'hye',
				self::COLUMN_LOCALE         => 'hy',
				self::COLUMN_HTTP_CODE      => 'hy-AM',
				self::COLUMN_PRIORITY       => 1,
			],
			'ia'    => [
				self::COLUMN_ENGLISH_NAME   => 'Interlingua',
				self::COLUMN_NATIVE_NAME    => 'Interlingua',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ia',
				self::COLUMN_ISO_639_2_CODE => 'ina',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ia',
				self::COLUMN_PRIORITY       => 1,
			],
			'id'    => [
				self::COLUMN_ENGLISH_NAME   => 'Indonesian',
				self::COLUMN_NATIVE_NAME    => 'Bahasa Indonesia',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'id',
				self::COLUMN_ISO_639_2_CODE => 'ind',
				self::COLUMN_LOCALE         => 'id_ID',
				self::COLUMN_HTTP_CODE      => 'id-ID',
				self::COLUMN_PRIORITY       => 1,
			],
			'ike'   => [
				self::COLUMN_ENGLISH_NAME   => 'Inuktitut',
				self::COLUMN_NATIVE_NAME    => 'ᐃᓄᒃᑎᑐᑦ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'iu',
				self::COLUMN_ISO_639_2_CODE => 'iku',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'iu',
				self::COLUMN_PRIORITY       => 1,
			],
			'ilo'   => [
				self::COLUMN_ENGLISH_NAME   => 'Iloko',
				self::COLUMN_NATIVE_NAME    => 'Pagsasao nga Iloko',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'is'    => [
				self::COLUMN_ENGLISH_NAME   => 'Icelandic',
				self::COLUMN_NATIVE_NAME    => 'Íslenska',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'is',
				self::COLUMN_ISO_639_2_CODE => 'isl',
				self::COLUMN_LOCALE         => 'is_IS',
				self::COLUMN_HTTP_CODE      => 'is-IS',
				self::COLUMN_PRIORITY       => 1,
			],
			'it'    => [
				self::COLUMN_ENGLISH_NAME   => 'Italian',
				self::COLUMN_NATIVE_NAME    => 'Italiano',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'it',
				self::COLUMN_ISO_639_2_CODE => 'ita',
				self::COLUMN_LOCALE         => 'it_IT',
				self::COLUMN_HTTP_CODE      => 'it-IT',
				self::COLUMN_PRIORITY       => 1,
			],
			'ja'    => [
				self::COLUMN_ENGLISH_NAME   => 'Japanese',
				self::COLUMN_NATIVE_NAME    => '日本語',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ja',
				self::COLUMN_ISO_639_2_CODE => 'jpn',
				self::COLUMN_LOCALE         => 'ja',
				self::COLUMN_HTTP_CODE      => 'ja-JP',
				self::COLUMN_PRIORITY       => 1,
			],
			'jv'    => [
				self::COLUMN_ENGLISH_NAME   => 'Javanese',
				self::COLUMN_NATIVE_NAME    => 'Basa Jawa',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'jv',
				self::COLUMN_ISO_639_2_CODE => 'jav',
				self::COLUMN_LOCALE         => 'jv_ID',
				self::COLUMN_HTTP_CODE      => 'jv-ID',
				self::COLUMN_PRIORITY       => 1,
			],
			'ka'    => [
				self::COLUMN_ENGLISH_NAME   => 'Georgian',
				self::COLUMN_NATIVE_NAME    => 'ქართული',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ka',
				self::COLUMN_ISO_639_2_CODE => 'kat',
				self::COLUMN_LOCALE         => 'ka_GE',
				self::COLUMN_HTTP_CODE      => 'ka-GE',
				self::COLUMN_PRIORITY       => 1,
			],
			'rw'    => [
				self::COLUMN_ENGLISH_NAME   => 'Kinyarwanda',
				self::COLUMN_NATIVE_NAME    => 'Kinyarwanda',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'rw',
				self::COLUMN_ISO_639_2_CODE => 'kin',
				self::COLUMN_LOCALE         => 'kin',
				self::COLUMN_HTTP_CODE      => 'rw',
				self::COLUMN_PRIORITY       => 1,
			],
			'kk'    => [
				self::COLUMN_ENGLISH_NAME   => 'Kazakh',
				self::COLUMN_NATIVE_NAME    => 'Қазақ тілі',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'kk',
				self::COLUMN_ISO_639_2_CODE => 'kaz',
				self::COLUMN_LOCALE         => 'kk',
				self::COLUMN_HTTP_CODE      => 'kk',
				self::COLUMN_PRIORITY       => 1,
			],
			'km'    => [
				self::COLUMN_ENGLISH_NAME   => 'Khmer',
				self::COLUMN_NATIVE_NAME    => 'ភាសាខ្មែរ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'km',
				self::COLUMN_ISO_639_2_CODE => 'khm',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'km-KH',
				self::COLUMN_PRIORITY       => 1,
			],
			'kn'    => [
				self::COLUMN_ENGLISH_NAME   => 'Kannada',
				self::COLUMN_NATIVE_NAME    => 'ಕನ್ನಡ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'kn',
				self::COLUMN_ISO_639_2_CODE => 'kan',
				self::COLUMN_LOCALE         => 'kn',
				self::COLUMN_HTTP_CODE      => 'kn',
				self::COLUMN_PRIORITY       => 1,
			],
			'ko'    => [
				self::COLUMN_ENGLISH_NAME   => 'Korean',
				self::COLUMN_NATIVE_NAME    => '한국어',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ko',
				self::COLUMN_ISO_639_2_CODE => 'kor',
				self::COLUMN_LOCALE         => 'ko_KR',
				self::COLUMN_HTTP_CODE      => 'ko-KR',
				self::COLUMN_PRIORITY       => 1,
			],
			'ks'    => [
				self::COLUMN_ENGLISH_NAME   => 'Kashmiri',
				self::COLUMN_NATIVE_NAME    => 'कश्मीरी',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ks',
				self::COLUMN_ISO_639_2_CODE => 'kas',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ks',
				self::COLUMN_PRIORITY       => 1,
			],
			'ku'    => [
				self::COLUMN_ENGLISH_NAME   => 'Kurdish (Kurmanji)',
				self::COLUMN_NATIVE_NAME    => 'Kurdî',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ku',
				self::COLUMN_ISO_639_2_CODE => 'kur',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'ku-TR',
				self::COLUMN_PRIORITY       => 1,
			],
			'ky'    => [
				self::COLUMN_ENGLISH_NAME   => 'Kyrgyz',
				self::COLUMN_NATIVE_NAME    => 'кыргыз тили',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ky',
				self::COLUMN_ISO_639_2_CODE => 'kir',
				self::COLUMN_LOCALE         => 'ky_KY',
				self::COLUMN_HTTP_CODE      => 'ky-KY',
				self::COLUMN_PRIORITY       => 1,
			],
			'la'    => [
				self::COLUMN_ENGLISH_NAME   => 'Latin',
				self::COLUMN_NATIVE_NAME    => 'latine',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'la',
				self::COLUMN_ISO_639_2_CODE => 'lat',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'la-VA',
				self::COLUMN_PRIORITY       => 1,
			],
			'lb'    => [
				self::COLUMN_ENGLISH_NAME   => 'Luxembourgish',
				self::COLUMN_NATIVE_NAME    => 'Lëtzebuergesch',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'lb',
				self::COLUMN_ISO_639_2_CODE => 'ltz',
				self::COLUMN_LOCALE         => 'lb_LU',
				self::COLUMN_HTTP_CODE      => 'lb-LU',
				self::COLUMN_PRIORITY       => 1,
			],
			'li'    => [
				self::COLUMN_ENGLISH_NAME   => 'Limburgish',
				self::COLUMN_NATIVE_NAME    => 'Limburgs',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'li',
				self::COLUMN_ISO_639_2_CODE => 'lim',
				self::COLUMN_LOCALE         => 'li',
				self::COLUMN_HTTP_CODE      => 'li',
				self::COLUMN_PRIORITY       => 1,
			],
			'lo'    => [
				self::COLUMN_ENGLISH_NAME   => 'Lao',
				self::COLUMN_NATIVE_NAME    => 'ພາສາລາວ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'lo',
				self::COLUMN_ISO_639_2_CODE => 'lao',
				self::COLUMN_LOCALE         => 'lo',
				self::COLUMN_HTTP_CODE      => 'lo',
				self::COLUMN_PRIORITY       => 1,
			],
			'lt'    => [
				self::COLUMN_ENGLISH_NAME   => 'Lithuanian',
				self::COLUMN_NATIVE_NAME    => 'lietuvių kalba',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'lt',
				self::COLUMN_ISO_639_2_CODE => 'lit',
				self::COLUMN_LOCALE         => 'lt_LT',
				self::COLUMN_HTTP_CODE      => 'lt-LT',
				self::COLUMN_PRIORITY       => 1,
			],
			'lv'    => [
				self::COLUMN_ENGLISH_NAME   => 'Latvian',
				self::COLUMN_NATIVE_NAME    => 'latviešu valoda',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'lv',
				self::COLUMN_ISO_639_2_CODE => 'lav',
				self::COLUMN_LOCALE         => 'lv',
				self::COLUMN_HTTP_CODE      => 'lv-LV',
				self::COLUMN_PRIORITY       => 1,
			],
			'me'    => [
				self::COLUMN_ENGLISH_NAME   => 'Montenegrin',
				self::COLUMN_NATIVE_NAME    => 'Crnogorski jezik',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'me',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => 'me_ME',
				self::COLUMN_HTTP_CODE      => 'me-ME',
				self::COLUMN_PRIORITY       => 1,
			],
			'mg'    => [
				self::COLUMN_ENGLISH_NAME   => 'Malagasy',
				self::COLUMN_NATIVE_NAME    => 'Malagasy',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'mg',
				self::COLUMN_ISO_639_2_CODE => 'mlg',
				self::COLUMN_LOCALE         => 'mg_MG',
				self::COLUMN_HTTP_CODE      => 'mg-MG',
				self::COLUMN_PRIORITY       => 1,
			],
			'mhr'   => [
				self::COLUMN_ENGLISH_NAME   => 'Mari (Meadow)',
				self::COLUMN_NATIVE_NAME    => 'олык марий',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'mk'    => [
				self::COLUMN_ENGLISH_NAME   => 'Macedonian',
				self::COLUMN_NATIVE_NAME    => 'македонски јазик',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'mk',
				self::COLUMN_ISO_639_2_CODE => 'mkd',
				self::COLUMN_LOCALE         => 'mk_MK',
				self::COLUMN_HTTP_CODE      => 'mk-MK',
				self::COLUMN_PRIORITY       => 1,
			],
			'ml'    => [
				self::COLUMN_ENGLISH_NAME   => 'Malayalam',
				self::COLUMN_NATIVE_NAME    => 'മലയാളം',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ml',
				self::COLUMN_ISO_639_2_CODE => 'mal',
				self::COLUMN_LOCALE         => 'ml_IN',
				self::COLUMN_HTTP_CODE      => 'ml-IN',
				self::COLUMN_PRIORITY       => 1,
			],
			'mn'    => [
				self::COLUMN_ENGLISH_NAME   => 'Mongolian',
				self::COLUMN_NATIVE_NAME    => 'Монгол',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'mn',
				self::COLUMN_ISO_639_2_CODE => 'mon',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'mn',
				self::COLUMN_PRIORITY       => 1,
			],
			'mr'    => [
				self::COLUMN_ENGLISH_NAME   => 'Marathi',
				self::COLUMN_NATIVE_NAME    => 'मराठी',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'mr',
				self::COLUMN_ISO_639_2_CODE => 'mar',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'mr',
				self::COLUMN_PRIORITY       => 1,
			],
			'mri'   => [
				self::COLUMN_ENGLISH_NAME   => 'Maori',
				self::COLUMN_NATIVE_NAME    => 'te reo Māori',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'mi',
				self::COLUMN_ISO_639_2_CODE => 'mri',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'mi',
				self::COLUMN_PRIORITY       => 1,
			],
			'mrj'   => [
				self::COLUMN_ENGLISH_NAME   => 'Mari (Hill)',
				self::COLUMN_NATIVE_NAME    => 'кырык мары',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'ms'    => [
				self::COLUMN_ENGLISH_NAME   => 'Malay',
				self::COLUMN_NATIVE_NAME    => 'bahasa Melayu',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ms',
				self::COLUMN_ISO_639_2_CODE => 'msa',
				self::COLUMN_LOCALE         => 'ms_MY',
				self::COLUMN_HTTP_CODE      => 'ms-MY',
				self::COLUMN_PRIORITY       => 1,
			],
			'mwl'   => [
				self::COLUMN_ENGLISH_NAME   => 'Mirandese',
				self::COLUMN_NATIVE_NAME    => 'Mirandés',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'mya'   => [
				self::COLUMN_ENGLISH_NAME   => 'Burmese',
				self::COLUMN_NATIVE_NAME    => 'ဗမာစာ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'my',
				self::COLUMN_ISO_639_2_CODE => 'mya',
				self::COLUMN_LOCALE         => 'my_MM',
				self::COLUMN_HTTP_CODE      => 'my-MM',
				self::COLUMN_PRIORITY       => 1,
			],
			'ne'    => [
				self::COLUMN_ENGLISH_NAME   => 'Nepali',
				self::COLUMN_NATIVE_NAME    => 'नेपाली',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ne',
				self::COLUMN_ISO_639_2_CODE => 'nep',
				self::COLUMN_LOCALE         => 'ne_NP',
				self::COLUMN_HTTP_CODE      => 'ne-NP',
				self::COLUMN_PRIORITY       => 1,
			],
			'nb'    => [
				self::COLUMN_ENGLISH_NAME   => 'Norwegian (Bokmål)',
				self::COLUMN_NATIVE_NAME    => 'Norsk bokmål',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'nb',
				self::COLUMN_ISO_639_2_CODE => 'nob',
				self::COLUMN_LOCALE         => 'nb_NO',
				self::COLUMN_HTTP_CODE      => 'nb-NO',
				self::COLUMN_PRIORITY       => 1,
			],
			'nl'    => [
				self::COLUMN_ENGLISH_NAME   => 'Dutch',
				self::COLUMN_NATIVE_NAME    => 'Nederlands',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'nl',
				self::COLUMN_ISO_639_2_CODE => 'nld',
				self::COLUMN_LOCALE         => 'nl_NL',
				self::COLUMN_HTTP_CODE      => 'nl-NL',
				self::COLUMN_PRIORITY       => 1,
			],
			'nl-be' => [
				self::COLUMN_ENGLISH_NAME   => 'Dutch (Belgium)',
				self::COLUMN_NATIVE_NAME    => 'Nederlands (België)',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'nl',
				self::COLUMN_ISO_639_2_CODE => 'nld',
				self::COLUMN_LOCALE         => 'nl_BE',
				self::COLUMN_HTTP_CODE      => 'nl-BE',
				self::COLUMN_PRIORITY       => 1,
			],
			'nn'    => [
				self::COLUMN_ENGLISH_NAME   => 'Norwegian (Nynorsk)',
				self::COLUMN_NATIVE_NAME    => 'Norsk nynorsk',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'nn',
				self::COLUMN_ISO_639_2_CODE => 'nno',
				self::COLUMN_LOCALE         => 'nn_NO',
				self::COLUMN_HTTP_CODE      => 'nn-NO',
				self::COLUMN_PRIORITY       => 1,
			],
			'no'    => [
				self::COLUMN_ENGLISH_NAME   => 'Norwegian',
				self::COLUMN_NATIVE_NAME    => 'Norsk',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'no',
				self::COLUMN_ISO_639_2_CODE => 'nor',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'no',
				self::COLUMN_PRIORITY       => 1,
			],
			'oc'    => [
				self::COLUMN_ENGLISH_NAME   => 'Occitan',
				self::COLUMN_NATIVE_NAME    => 'Occitan',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'oc',
				self::COLUMN_ISO_639_2_CODE => 'oci',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'oc',
				self::COLUMN_PRIORITY       => 1,
			],
			'os'    => [
				self::COLUMN_ENGLISH_NAME   => 'Ossetic',
				self::COLUMN_NATIVE_NAME    => 'Ирон',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'os',
				self::COLUMN_ISO_639_2_CODE => 'oss',
				self::COLUMN_LOCALE         => 'os',
				self::COLUMN_HTTP_CODE      => 'os',
				self::COLUMN_PRIORITY       => 1,
			],
			'pa'    => [
				self::COLUMN_ENGLISH_NAME   => 'Panjabi',
				self::COLUMN_NATIVE_NAME    => 'ਪੰਜਾਬੀ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'pa',
				self::COLUMN_ISO_639_2_CODE => 'pan',
				self::COLUMN_LOCALE         => 'pa_IN',
				self::COLUMN_HTTP_CODE      => 'pa-IN',
				self::COLUMN_PRIORITY       => 1,
			],
			'pl'    => [
				self::COLUMN_ENGLISH_NAME   => 'Polish',
				self::COLUMN_NATIVE_NAME    => 'Polski',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'pl',
				self::COLUMN_ISO_639_2_CODE => 'pol',
				self::COLUMN_LOCALE         => 'pl_PL',
				self::COLUMN_HTTP_CODE      => 'pl-PL',
				self::COLUMN_PRIORITY       => 1,
			],
			'pt-br' => [
				self::COLUMN_ENGLISH_NAME   => 'Portuguese (Brazil)',
				self::COLUMN_NATIVE_NAME    => 'Português do Brasil',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'pt',
				self::COLUMN_ISO_639_2_CODE => 'por',
				self::COLUMN_LOCALE         => 'pt_BR',
				self::COLUMN_HTTP_CODE      => 'pt-BR',
				self::COLUMN_PRIORITY       => 1,
			],
			'pt'    => [
				self::COLUMN_ENGLISH_NAME   => 'Portuguese (Portugal)',
				self::COLUMN_NATIVE_NAME    => 'Português',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'pt',
				self::COLUMN_ISO_639_2_CODE => 'por',
				self::COLUMN_LOCALE         => 'pt_PT',
				self::COLUMN_HTTP_CODE      => 'pt-PT',
				self::COLUMN_PRIORITY       => 1,
			],
			'ps'    => [
				self::COLUMN_ENGLISH_NAME   => 'Pashto',
				self::COLUMN_NATIVE_NAME    => 'پښتو',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'ps',
				self::COLUMN_ISO_639_2_CODE => 'pus',
				self::COLUMN_LOCALE         => 'ps',
				self::COLUMN_HTTP_CODE      => 'ps-AF',
				self::COLUMN_PRIORITY       => 1,
			],
			'ro'    => [
				self::COLUMN_ENGLISH_NAME   => 'Romanian',
				self::COLUMN_NATIVE_NAME    => 'Română',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ro',
				self::COLUMN_ISO_639_2_CODE => 'ron',
				self::COLUMN_LOCALE         => 'ro_RO',
				self::COLUMN_HTTP_CODE      => 'ro-RO',
				self::COLUMN_PRIORITY       => 1,
			],
			'ru'    => [
				self::COLUMN_ENGLISH_NAME   => 'Russian',
				self::COLUMN_NATIVE_NAME    => 'Русский',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ru',
				self::COLUMN_ISO_639_2_CODE => 'rus',
				self::COLUMN_LOCALE         => 'ru_RU',
				self::COLUMN_HTTP_CODE      => 'ru-RU',
				self::COLUMN_PRIORITY       => 1,
			],
			'ru-ua' => [
				self::COLUMN_ENGLISH_NAME   => 'Russian (Ukraine)',
				self::COLUMN_NATIVE_NAME    => 'украї́нська мо́ва',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ru',
				self::COLUMN_ISO_639_2_CODE => 'rus',
				self::COLUMN_LOCALE         => 'ru_UA',
				self::COLUMN_HTTP_CODE      => 'ru-UA',
				self::COLUMN_PRIORITY       => 1,
			],
			'rue'   => [
				self::COLUMN_ENGLISH_NAME   => 'Rusyn',
				self::COLUMN_NATIVE_NAME    => 'Русиньскый',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => 'rue',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'rup'   => [
				self::COLUMN_ENGLISH_NAME   => 'Aromanian',
				self::COLUMN_NATIVE_NAME    => 'Armãneashce',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => 'rup',
				self::COLUMN_LOCALE         => 'rup_MK',
				self::COLUMN_HTTP_CODE      => 'rup-MK',
				self::COLUMN_PRIORITY       => 1,
			],
			'sah'   => [
				self::COLUMN_ENGLISH_NAME   => 'Yakut',
				self::COLUMN_NATIVE_NAME    => 'Sakha',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => 'sah',
				self::COLUMN_LOCALE         => 'sah',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'sa-in' => [
				self::COLUMN_ENGLISH_NAME   => 'Sanskrit',
				self::COLUMN_NATIVE_NAME    => 'भारतम्',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sa',
				self::COLUMN_ISO_639_2_CODE => 'san',
				self::COLUMN_LOCALE         => 'sa_IN',
				self::COLUMN_HTTP_CODE      => 'sa-IN',
				self::COLUMN_PRIORITY       => 1,
			],
			'sd'    => [
				self::COLUMN_ENGLISH_NAME   => 'Sindhi',
				self::COLUMN_NATIVE_NAME    => 'سندھ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sd',
				self::COLUMN_ISO_639_2_CODE => 'snd',
				self::COLUMN_LOCALE         => 'sd_PK',
				self::COLUMN_HTTP_CODE      => 'sd-PK',
				self::COLUMN_PRIORITY       => 1,
			],
			'si'    => [
				self::COLUMN_ENGLISH_NAME   => 'Sinhala',
				self::COLUMN_NATIVE_NAME    => 'සිංහල',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'si',
				self::COLUMN_ISO_639_2_CODE => 'sin',
				self::COLUMN_LOCALE         => 'si_LK',
				self::COLUMN_HTTP_CODE      => 'si-LK',
				self::COLUMN_PRIORITY       => 1,
			],
			'sk'    => [
				self::COLUMN_ENGLISH_NAME   => 'Slovak',
				self::COLUMN_NATIVE_NAME    => 'Slovenčina',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sk',
				self::COLUMN_ISO_639_2_CODE => 'slk',
				self::COLUMN_LOCALE         => 'sk_SK',
				self::COLUMN_HTTP_CODE      => 'sk-SK',
				self::COLUMN_PRIORITY       => 1,
			],
			'sl'    => [
				self::COLUMN_ENGLISH_NAME   => 'Slovenian',
				self::COLUMN_NATIVE_NAME    => 'slovenščina',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sl',
				self::COLUMN_ISO_639_2_CODE => 'slv',
				self::COLUMN_LOCALE         => 'sl_SI',
				self::COLUMN_HTTP_CODE      => 'sl-SI',
				self::COLUMN_PRIORITY       => 1,
			],
			'so'    => [
				self::COLUMN_ENGLISH_NAME   => 'Somali',
				self::COLUMN_NATIVE_NAME    => 'Afsoomaali',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'so',
				self::COLUMN_ISO_639_2_CODE => 'som',
				self::COLUMN_LOCALE         => 'so_SO',
				self::COLUMN_HTTP_CODE      => 'so-SO',
				self::COLUMN_PRIORITY       => 1,
			],
			'sq'    => [
				self::COLUMN_ENGLISH_NAME   => 'Albanian',
				self::COLUMN_NATIVE_NAME    => 'Shqip',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sq',
				self::COLUMN_ISO_639_2_CODE => 'sqi',
				self::COLUMN_LOCALE         => 'sq',
				self::COLUMN_HTTP_CODE      => 'sq-AL',
				self::COLUMN_PRIORITY       => 1,
			],
			'sr'    => [
				self::COLUMN_ENGLISH_NAME   => 'Serbian',
				self::COLUMN_NATIVE_NAME    => 'Српски језик',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sr',
				self::COLUMN_ISO_639_2_CODE => 'srp',
				self::COLUMN_LOCALE         => 'sr_RS',
				self::COLUMN_HTTP_CODE      => 'sr-RS',
				self::COLUMN_PRIORITY       => 1,
			],
			'srd'   => [
				self::COLUMN_ENGLISH_NAME   => 'Sardinian',
				self::COLUMN_NATIVE_NAME    => 'sardu',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sc',
				self::COLUMN_ISO_639_2_CODE => 'srd',
				self::COLUMN_LOCALE         => 'srd',
				self::COLUMN_HTTP_CODE      => 'sc',
				self::COLUMN_PRIORITY       => 1,
			],
			'su'    => [
				self::COLUMN_ENGLISH_NAME   => 'Sundanese',
				self::COLUMN_NATIVE_NAME    => 'Basa Sunda',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'su',
				self::COLUMN_ISO_639_2_CODE => 'sun',
				self::COLUMN_LOCALE         => 'su_ID',
				self::COLUMN_HTTP_CODE      => 'su-ID',
				self::COLUMN_PRIORITY       => 1,
			],
			'sv'    => [
				self::COLUMN_ENGLISH_NAME   => 'Swedish',
				self::COLUMN_NATIVE_NAME    => 'Svenska',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sv',
				self::COLUMN_ISO_639_2_CODE => 'swe',
				self::COLUMN_LOCALE         => 'sv_SE',
				self::COLUMN_HTTP_CODE      => 'sv-SE',
				self::COLUMN_PRIORITY       => 1,
			],
			'sw'    => [
				self::COLUMN_ENGLISH_NAME   => 'Swahili',
				self::COLUMN_NATIVE_NAME    => 'Kiswahili',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'sw',
				self::COLUMN_ISO_639_2_CODE => 'swa',
				self::COLUMN_LOCALE         => 'sw',
				self::COLUMN_HTTP_CODE      => 'sw-KE',
				self::COLUMN_PRIORITY       => 1,
			],
			'ta'    => [
				self::COLUMN_ENGLISH_NAME   => 'Tamil',
				self::COLUMN_NATIVE_NAME    => 'தமிழ்',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ta',
				self::COLUMN_ISO_639_2_CODE => 'tam',
				self::COLUMN_LOCALE         => 'ta_IN',
				self::COLUMN_HTTP_CODE      => 'ta-IN',
				self::COLUMN_PRIORITY       => 1,
			],
			'ta-lk' => [
				self::COLUMN_ENGLISH_NAME   => 'Tamil (Sri Lanka)',
				self::COLUMN_NATIVE_NAME    => 'தமிழ்',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ta',
				self::COLUMN_ISO_639_2_CODE => 'tam',
				self::COLUMN_LOCALE         => 'ta_LK',
				self::COLUMN_HTTP_CODE      => 'ta-LK',
				self::COLUMN_PRIORITY       => 1,
			],
			'te'    => [
				self::COLUMN_ENGLISH_NAME   => 'Telugu',
				self::COLUMN_NATIVE_NAME    => 'తెలుగు',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'te',
				self::COLUMN_ISO_639_2_CODE => 'tel',
				self::COLUMN_LOCALE         => 'te',
				self::COLUMN_HTTP_CODE      => 'te-IN',
				self::COLUMN_PRIORITY       => 1,
			],
			'tg'    => [
				self::COLUMN_ENGLISH_NAME   => 'Tajik',
				self::COLUMN_NATIVE_NAME    => 'тоҷикӣ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'tg',
				self::COLUMN_ISO_639_2_CODE => 'tgk',
				self::COLUMN_LOCALE         => 'tg',
				self::COLUMN_HTTP_CODE      => 'tg',
				self::COLUMN_PRIORITY       => 1,
			],
			'th'    => [
				self::COLUMN_ENGLISH_NAME   => 'Thai',
				self::COLUMN_NATIVE_NAME    => 'ไทย',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'th',
				self::COLUMN_ISO_639_2_CODE => 'tha',
				self::COLUMN_LOCALE         => 'th',
				self::COLUMN_HTTP_CODE      => 'th-TH',
				self::COLUMN_PRIORITY       => 1,
			],
			'tlh'   => [
				self::COLUMN_ENGLISH_NAME   => 'Klingon',
				self::COLUMN_NATIVE_NAME    => 'TlhIngan',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => 'tlh',
				self::COLUMN_HTTP_CODE      => 'tlh',
				self::COLUMN_PRIORITY       => 1,
			],
			'tl'    => [
				self::COLUMN_ENGLISH_NAME   => 'Tagalog',
				self::COLUMN_NATIVE_NAME    => 'Tagalog',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'tl',
				self::COLUMN_ISO_639_2_CODE => 'tgl',
				self::COLUMN_LOCALE         => 'tl',
				self::COLUMN_HTTP_CODE      => 'tl-PH',
				self::COLUMN_PRIORITY       => 1,
			],
			'tr'    => [
				self::COLUMN_ENGLISH_NAME   => 'Turkish',
				self::COLUMN_NATIVE_NAME    => 'Türkçe',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'tr',
				self::COLUMN_ISO_639_2_CODE => 'tur',
				self::COLUMN_LOCALE         => 'tr_TR',
				self::COLUMN_HTTP_CODE      => 'tr-TR',
				self::COLUMN_PRIORITY       => 1,
			],
			'tt'    => [
				self::COLUMN_ENGLISH_NAME   => 'Tatar',
				self::COLUMN_NATIVE_NAME    => 'Татар теле',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'tt',
				self::COLUMN_ISO_639_2_CODE => 'tat',
				self::COLUMN_LOCALE         => 'tt_RU',
				self::COLUMN_HTTP_CODE      => 'tt-RU',
				self::COLUMN_PRIORITY       => 1,
			],
			'tuk'   => [
				self::COLUMN_ENGLISH_NAME   => 'Turkmen',
				self::COLUMN_NATIVE_NAME    => 'Türkmençe',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'tk',
				self::COLUMN_ISO_639_2_CODE => 'tuk',
				self::COLUMN_LOCALE         => 'tuk',
				self::COLUMN_HTTP_CODE      => 'tk',
				self::COLUMN_PRIORITY       => 1,
			],
			'tzm'   => [
				self::COLUMN_ENGLISH_NAME   => 'Tamazight (Central Atlas)',
				self::COLUMN_NATIVE_NAME    => 'ⵜⴰⵎⴰⵣⵉⵖⵜ',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => 'tzm',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'udm'   => [
				self::COLUMN_ENGLISH_NAME   => 'Udmurt',
				self::COLUMN_NATIVE_NAME    => 'удмурт кыл',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'ug'    => [
				self::COLUMN_ENGLISH_NAME   => 'Uyghur',
				self::COLUMN_NATIVE_NAME    => 'Uyƣurqə',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ug',
				self::COLUMN_ISO_639_2_CODE => 'uig',
				self::COLUMN_LOCALE         => 'ug_CN',
				self::COLUMN_HTTP_CODE      => 'ug-CN',
				self::COLUMN_PRIORITY       => 1,
			],
			'uk'    => [
				self::COLUMN_ENGLISH_NAME   => 'Ukrainian',
				self::COLUMN_NATIVE_NAME    => 'Українська',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'uk',
				self::COLUMN_ISO_639_2_CODE => 'ukr',
				self::COLUMN_LOCALE         => 'uk',
				self::COLUMN_HTTP_CODE      => 'uk-UA',
				self::COLUMN_PRIORITY       => 1,
			],
			'ur'    => [
				self::COLUMN_ENGLISH_NAME   => 'Urdu',
				self::COLUMN_NATIVE_NAME    => 'اردو',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'ur',
				self::COLUMN_ISO_639_2_CODE => 'urd',
				self::COLUMN_LOCALE         => 'ur',
				self::COLUMN_HTTP_CODE      => 'ur',
				self::COLUMN_PRIORITY       => 1,
			],
			'uz'    => [
				self::COLUMN_ENGLISH_NAME   => 'Uzbek',
				self::COLUMN_NATIVE_NAME    => 'O‘zbekcha',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'uz',
				self::COLUMN_ISO_639_2_CODE => 'uzb',
				self::COLUMN_LOCALE         => 'uz_UZ',
				self::COLUMN_HTTP_CODE      => 'uz-UZ',
				self::COLUMN_PRIORITY       => 1,
			],
			'vec'   => [
				self::COLUMN_ENGLISH_NAME   => 'Venetian',
				self::COLUMN_NATIVE_NAME    => 'vèneta',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'vi'    => [
				self::COLUMN_ENGLISH_NAME   => 'Vietnamese',
				self::COLUMN_NATIVE_NAME    => 'Tiếng Việt',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'vi',
				self::COLUMN_ISO_639_2_CODE => 'vie',
				self::COLUMN_LOCALE         => 'vi',
				self::COLUMN_HTTP_CODE      => 'vi-VN',
				self::COLUMN_PRIORITY       => 1,
			],
			'wa'    => [
				self::COLUMN_ENGLISH_NAME   => 'Walloon',
				self::COLUMN_NATIVE_NAME    => 'Walon',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'wa',
				self::COLUMN_ISO_639_2_CODE => 'wln',
				self::COLUMN_LOCALE         => 'wa',
				self::COLUMN_HTTP_CODE      => 'wa',
				self::COLUMN_PRIORITY       => 1,
			],
			'xmf'   => [
				self::COLUMN_ENGLISH_NAME   => 'Mingrelian',
				self::COLUMN_NATIVE_NAME    => 'მარგალური ნინა',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => '',
				self::COLUMN_ISO_639_2_CODE => '',
				self::COLUMN_LOCALE         => 'xmf',
				self::COLUMN_HTTP_CODE      => '',
				self::COLUMN_PRIORITY       => 1,
			],
			'yi'    => [
				self::COLUMN_ENGLISH_NAME   => 'Yiddish',
				self::COLUMN_NATIVE_NAME    => 'ייִדיש',
				self::COLUMN_RTL            => 1,
				self::COLUMN_ISO_639_1_CODE => 'yi',
				self::COLUMN_ISO_639_2_CODE => 'yid',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'yi',
				self::COLUMN_PRIORITY       => 1,
			],
			'yo'    => [
				self::COLUMN_ENGLISH_NAME   => 'Yorùbá',
				self::COLUMN_NATIVE_NAME    => 'èdè Yorùbá',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'yo',
				self::COLUMN_ISO_639_2_CODE => 'yor',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'yo',
				self::COLUMN_PRIORITY       => 1,
			],
			'zh-cn' => [
				self::COLUMN_ENGLISH_NAME   => 'Chinese (China)',
				self::COLUMN_NATIVE_NAME    => '中文',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'zh',
				self::COLUMN_ISO_639_2_CODE => 'zho',
				self::COLUMN_LOCALE         => 'zh_CN',
				self::COLUMN_HTTP_CODE      => 'zh-CN',
				self::COLUMN_PRIORITY       => 1,
			],
			'zh-hk' => [
				self::COLUMN_ENGLISH_NAME   => 'Chinese (Hong Kong)',
				self::COLUMN_NATIVE_NAME    => '香港中文版	',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'zh',
				self::COLUMN_ISO_639_2_CODE => 'zho',
				self::COLUMN_LOCALE         => 'zh_HK',
				self::COLUMN_HTTP_CODE      => 'zh-HK',
				self::COLUMN_PRIORITY       => 1,
			],
			'zh-sg' => [
				self::COLUMN_ENGLISH_NAME   => 'Chinese (Singapore)',
				self::COLUMN_NATIVE_NAME    => '中文',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'zh',
				self::COLUMN_ISO_639_2_CODE => 'zho',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'zh-SG',
				self::COLUMN_PRIORITY       => 1,
			],
			'zh-tw' => [
				self::COLUMN_ENGLISH_NAME   => 'Chinese (Taiwan)',
				self::COLUMN_NATIVE_NAME    => '中文',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'zh',
				self::COLUMN_ISO_639_2_CODE => 'zho',
				self::COLUMN_LOCALE         => 'zh_TW',
				self::COLUMN_HTTP_CODE      => 'zh-TW',
				self::COLUMN_PRIORITY       => 1,
			],
			'zh'    => [
				self::COLUMN_ENGLISH_NAME   => 'Chinese',
				self::COLUMN_NATIVE_NAME    => '中文',
				self::COLUMN_RTL            => 0,
				self::COLUMN_ISO_639_1_CODE => 'zh',
				self::COLUMN_ISO_639_2_CODE => 'zho',
				self::COLUMN_LOCALE         => '',
				self::COLUMN_HTTP_CODE      => 'zh',
				self::COLUMN_PRIORITY       => 1,
			],
		];

		$rows = array_map( function ( array $row ) {

			return '(\'' . implode( '\',\'', $row ) . '\')';
		}, $rows );

		return implode( ',', $rows );
	}

	/**
	 * Returns the SQL string for all (unique) keys.
	 *
	 * @since 3.0.0
	 *
	 * @return string The SQL string for all (unique) keys.
	 */
	public function keys_sql(): string {

		// Due to dbDelta: KEY (not INDEX), and no spaces inside brackets!
		return sprintf(
			'KEY http_code (%1$s)',
			self::COLUMN_HTTP_CODE
		);
	}

	/**
	 * Returns the table name.
	 *
	 * @since 3.0.0
	 *
	 * @return string The table name.
	 */
	public function name(): string {

		return "{$this->prefix}mlp_languages";
	}

	/**
	 * Returns the primary key.
	 *
	 * @since 3.0.0
	 *
	 * @return string The primary key.
	 */
	public function primary_key(): string {

		return self::COLUMN_ID;
	}

	/**
	 * Returns the table schema.
	 *
	 * @since 3.0.0
	 *
	 * @return string[] An array with column names as keys and the according SQL definitions as values.
	 */
	public function schema(): array {

		return [
			self::COLUMN_ID             => 'bigint(20) unsigned NOT NULL auto_increment',
			self::COLUMN_ENGLISH_NAME   => 'tinytext',
			self::COLUMN_NATIVE_NAME    => 'tinytext',
			self::COLUMN_CUSTOM_NAME    => 'tinytext',
			self::COLUMN_RTL            => 'tinyint(1) unsigned DEFAULT 0',
			self::COLUMN_ISO_639_1_CODE => 'varchar(20)',
			self::COLUMN_ISO_639_2_CODE => 'varchar(20)',
			self::COLUMN_LOCALE         => 'tinytext',
			self::COLUMN_HTTP_CODE      => 'varchar(20)',
			self::COLUMN_PRIORITY       => 'tinyint(1) unsigned DEFAULT 10',
		];
	}
}
